apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - visign-ai-deployment.yaml
  - visign-ai-service.yaml
  - visign-web-deployment.yaml
  - visign-web-service.yaml
images:
  - name: visign-ai
    newTag: ""
  - name: visign-web
    newTag: ""
