apiVersion: v1
kind: Service
metadata:
  name: visign-ai
  namespace: visign
  labels:
    app: visign-ai
spec:
  selector:
    app: visign-ai
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP