apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visign-prod
resources:
  - ../base
  - secrets-provider.yaml
  - ingress.yaml
images:
  - name: visignacrftll4r7kkywwy.azurecr.io/visign-ai
    newName: visignpacrftll4r7kkywwy.azurecr.io/visign-ai
    newTag: "main-058383ce0d7406de93f9bb66508ea4b4e3070a83"
  - name: visignacrftll4r7kkywwy.azurecr.io/visign-web
    newName: visignpacrftll4r7kkywwy.azurecr.io/visign-web
    newTag: "main-058383ce0d7406de93f9bb66508ea4b4e3070a83"
