apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: visign-kv-secrets
  namespace: visign-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3f954f5e-5da7-4e1d-aef6-952241a2b2da"
    keyvaultName: "visignpkvftll4r7kkywwy"
    cloudName: ""
    tenantId: "2dff09ac-2b3b-4182-9953-2b548e0d0b39"
    objects: |
      array:
        - |
          objectName: DATABASE-URL
          objectType: secret
        - |
          objectName: CLERK-PUBLISHABLE-KEY
          objectType: secret
        - |
          objectName: CLERK-SECRET-KEY
          objectType: secret
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
        - |
          objectName: TORCH-COMPUTE
          objectType: secret
  secretObjects:
    - secretName: visign-secrets
      type: Opaque
      data:
        - objectName: DATABASE-URL
          key: DATABASE_URL
        - objectName: CLERK-PUBLISHABLE-KEY
          key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        - objectName: CLERK-SECRET-KEY
          key: CLERK_SECRET_KEY
        - objectName: OPENAI-API-KEY
          key: OPENAI_API_KEY
        - objectName: TORCH-COMPUTE
          key: TORCH_COMPUTE