name: CI - AI

on:
  push:
    branches: [dev, main]
    paths:
      - "apps/ai/**"
      - ".github/workflows/**"

  pull_request:
    branches: [dev, main]
    paths:
      - "apps/ai/**"
      - ".github/workflows/**"

jobs:
  ci:
    uses: lengynthaovan/visign-gitops/.github/workflows/reusable-service-ci.yml@main
    with:
      project: visign
      service: ai
      service_type: python
      context_path: apps/ai
      dockerfile_path: apps/ai/Dockerfile
      image_name: visign-ai
      migration_enabled: false
      migration_image_name: ""
      migration_dockerfile_path: ""
      migration_build_target: ""
      gitops_values_dev: projects/visign/environments/dev/ai.values.yaml
      gitops_values_prod: projects/visign/environments/prod/ai.values.yaml
    secrets: inherit
