name: CI - Web

on:
  workflow_dispatch:

  push:
    branches: [dev, main]
    paths:
      - "visign/**"
      - ".github/workflows/**"

  pull_request:
    branches: [dev, main]
    paths:
      - "visign/**"
      - ".github/workflows/**"

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: visign-uit/visign-gitops/.github/workflows/reusable-service-ci.yml@main
    with:
      project: visign
      service: web
      service_type: node
      context_path: visign
      dockerfile_path: visign/Dockerfile
      image_name: visign-web
      migration_enabled: true
      migration_image_name: visign-web-migrator
      migration_dockerfile_path: visign/Dockerfile
      migration_build_target: migrator
      gitops_values_dev: projects/visign/environments/dev/web.values.yaml
      gitops_values_prod: projects/visign/environments/prod/web.values.yaml
    secrets: inherit

# trigger dev ci rerun
